sudo: required
services:
  - docker

script:
  - docker build --tag gtct/cowsay .
  - docker run gtct/cowsay

after_script:
  - docker images
  
before_deploy:
  - docker login -u $DH_USER -p $DH_PASS

deploy:
  provider: script
  script: docker push gtct/cowsay
  on:
    branch: master
