sudo: required
services:
  - docker

script:
  - docker build --tag gtct/cowsay .
  - docker run gtct/cowsay

after_success:
  - export IMAGE_NAME=gtct/cowsay
  - export TAG=$TRAVIS_BUILD_NUMBER
  - docker build -t $IMAGE_NAME:$TAG .
  - docker login -u $DH_USER -p $DH_PASS
  - docker push $IMAGE_NAME:$TAG
